####################################################
# What to be done om redhat only
####################################################

- name: ansible_role_thinlinc | Redhat | check if we're building on a supported os
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 16, 18, 20 and centos versions 6, 7!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ansible_distribution|lower == "redhat" and ansible_distribution_major_version|int in [8] 

- name: ansible_role_thinlinc |  Redhat |Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: ansible_role_thinlinc | Redhat |Enable codeready-builder repository
  shell: subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms || echo
  become: True

- name: ansible_role_thinlinc |  Redhat |Enable appstream repository
  shell: subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms  || echo
  become: True


- name: ansible_role_thinlinc |Redhat |Install the latest version of gnome desktop
  ansible.builtin.package:
    name:
      - wget
      - expect
      - xpra
      - Thunar
      - xfce4-panel
      - xfce4-session
      - xfce4-settings
      - xfconf
      - xfdesktop
      - xfwm4
      - NetworkManager
      - gdm
      - mousepad
      - openssh-askpass
      - thunar-archive-plugin
      - thunar-volman
      - tumbler
      - xfce-polkit
      - xfce4-appfinder
      - xfce4-power-manager
      - xfce4-pulseaudio-plugin
      - xfce4-screensaver
      - xfce4-terminal
      - pinentry-gtk
    state: latest

- name: ansible_role_thinlinc |Redhat |Install clean up old install
  become: yes
  command: "yum remove -y thinlinc-*"